server {
    listen      8088;
    listen      [::]:8088;

    server_name 221.121.4.77;

    root        /var/www/devops-hackathon-de001-duongtran1702/src;
    index       index.html;

    access_log  /var/log/nginx/ttduong-cntt1.access.log;
    error_log   /var/log/nginx/ttduong-cntt1.error.log;

    location / {
        allow all;
        try_files $uri $uri/ =404;
    }
}
